name: Builds

on:
  push:
    branches:
    - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload images artifact
        uses: actions/upload-artifact@v4
        with:
          name: validation
          path: images/