name: Builds

on:
  push:
    branches:
    - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload images artifact
        uses: actions/upload-artifact@v4
        with:
          name: validation
          path: images/

  histcmp_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up miniforge
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-variant: Miniforge3
          python-version: "3.12"
          channels: conda-forge

      - name: Install ROOT and histcmp
        shell: bash -l {0}
        run: |
          conda install -y root
          pip install histcmp==0.8.1

      - name: Test histcmp version
        shell: bash -l {0}
        run: CI/test.sh "$GITHUB_WORKSPACE" "$GITHUB_WORKSPACE"

